version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          echo 'export SeedUserPW=$(cat Keys/0cd0s0.txt)' >> $BASH_ENV
          source $BASH_ENV
      # build image
      - run: |
          docker info
          docker build -t marshalapi -f Dockerfile .
      # deploy the image
      - run: |
          docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
          docker tag marshalapi registry.heroku.com/$HEROKU_APP_NAME/web
          docker push registry.heroku.com/$HEROKU_APP_NAME/web                
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku container:release web -a $HEROKU_APP_NAME
